[package]
name = "cliquenet"
description = "A fully connected mesh network"
version.workspace = true
edition.workspace = true

[dependencies]
bon = { workspace = true }
bytes = { workspace = true }
bincode = { workspace = true }
nohash-hasher = { workspace = true }
parking_lot = { workspace = true }
rand = "0.9.2"
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }
quickcheck = { workspace = true }

