[package]
name = "cliquenet"
version = "0.1.0"
edition = "2024"
description = "A fully connected mesh network"

[features]
metrics = []

[dependencies]
bon = { workspace = true }
bytes = { workspace = true }
bimap = { workspace = true }
nohash-hasher = { workspace = true }
parking_lot = { workspace = true }
rand = "0.9.2"
snow = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
hotshot-types = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
portpicker = { workspace = true }
quickcheck = { workspace = true }
tracing-subscriber = { workspace = true }

[[bench]]
name = "bench1"
harness = false
