[package]
name = "cliquenet"
description = "A fully connected mesh network"
version.workspace = true
edition.workspace = true

[dependencies]
bon = { workspace = true }
bytes = { workspace = true }
bimap = "0.6.3"
bincode = { workspace = true }
bs58 = "0.5.1"
ed25519-compact = "2.2.0"
nohash-hasher = { workspace = true }
parking_lot = { workspace = true }
rand = "0.9.2"
serde = { workspace = true }
serde_bytes = { workspace = true }
snow = "0.10.0"
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }
quickcheck = { workspace = true }

