[package]
name = "cliquenet"
version = "0.1.0"
edition = "2024"
description = "A fully connected mesh network"

[features]
metrics = ["dep:hotshot-types"]

[dependencies]
bon = { workspace = true }
bytes = { workspace = true }
bimap = "0.6.3"
bs58 = "0.5.1"
ed25519-compact = "2.2.0"
nohash-hasher = { workspace = true }
parking_lot = { workspace = true }
rand = "0.9.2"
serde = { workspace = true }
serde_bytes = { workspace = true }
snow = { version = "0.10.0", features = ["ring-accelerated"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
# optional:
hotshot-types = { workspace = true, optional = true }

[dev-dependencies]
criterion = "0.8.1"
portpicker = { workspace = true }
quickcheck = { workspace = true }
tracing-subscriber = { workspace = true }

[[bench]]
name = "bench1"
harness = false
