network = "decaf"

[multisigs.espresso_labs]
status = "deployed"
address = "0xb76834e371b666feee48e5d7d9a97ca08b5a0620"
version = "1.4.1"
owners = [
    "0x74560e14de4426d1aa461801edc782ad653d9847",
    "0x811caa1c5c96bfe0ab12b2eeb542994b0c368627",
    "0x647e90723669b6bb163a46e8bfebcb95beb94849",
    "0x53d5385d897872bb8199309be70810fc09e58ce5",
    "0xf4b7676d9ec86d2011ab87855424219a97deb40c",
]
threshold = 2

[ops_timelock]
status = "deployed"
address = "0x0eb0ef3b5a46a444c38da452055bddb273550d5c"
min_delay = 600

[safe_exit_timelock]
status = "deployed"
address = "0x8e3b6563d683b87964104a2c3a4bf542bb70767f"
min_delay = 300

[stake_table]
status = "deployed"
address = "0x40304fbe94d5e7d1492dd90c53a2d63e8506a037"
owner = "0xb76834e371b666feee48e5d7d9a97ca08b5a0620"
version = "2.0.0"

[esp_token]
status = "deployed"
address = "0xb3e655a030e2e34a18b72757b40be086a8f43f3b"
owner = "0xb76834e371b666feee48e5d7d9a97ca08b5a0620"
version = "2.0.0"

[light_client]
status = "deployed"
address = "0x303872bb82a191771321d4828888920100d0b3e4"
owner = "0xb76834e371b666feee48e5d7d9a97ca08b5a0620"
version = "3.0.0"

[fee_contract]
status = "deployed"
address = "0x42835083fd1d3fc5d799b5f6815ae4bf2623e6d0"
owner = "0xb76834e371b666feee48e5d7d9a97ca08b5a0620"
version = "1.0.0"

[reward_claim]
status = "deployed"
address = "0xe81908e34dbb4ba01f27f8769264199727be50c8"
owner = "0x0000000000000000000000000000000000000000"
version = "1.0.0"
