[package]
name = "deployment-info"
description = "Tool to collect and output deployment information for Espresso Network contracts"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "deployment-info"
path = "src/main.rs"

[dependencies]
alloy = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
dotenvy = { workspace = true }
hotshot-contract-adapter = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
url = { workspace = true }

[dev-dependencies]
espresso-contract-deployer = { path = "../deployer" }
espresso-types = { workspace = true }
hotshot-state-prover = { workspace = true }
test-log = { workspace = true }
tracing-test = { workspace = true }

[lints]
workspace = true
