[route.total_minted_supply]
PATH = ["total_minted_supply"]
DOC = "Get the total supply of the espresso token, counting only tokens that have been minted. Notably, this does not include unminted tokens from (for example) unclaimed rewards, or other sources."
